name: flutter_map_geojson2
description: "GeoJSON layer for flutter_map"
version: 1.0.2
homepage: https://github.com/zverik/flutter_map_geojson2

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ">=7.0.0 <9.0.0"
  latlong2: ^0.9.0
  material_color_names: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
